site_name: What would Seweryn want to build?

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Sewer56

extra_css:
  - Reloaded/Stylesheets/extra.css

markdown_extensions:
  - admonition
  - tables
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tasklist
  - def_list
  - meta
  - md_in_html
  - attr_list
  - footnotes
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

theme:
  name: material
  palette:
    scheme: reloaded3-slate
  features:
    - navigation.instant

plugins:
  - search
  - exclude-unused-files:
      file_types_to_check: [ "psd", "7z", "kra" ]
      file_types_override_mode: append
      enabled: true
  - exclude:
      # Exclude the Theme's own files.
      glob:
        - Reloaded/Pages/*
        - Reloaded/docs/*
        - Reloaded/Readme.md
        - Reloaded/LICENSE
        - Reloaded/mkdocs.yml

nav:
  - Home: index.md
  - Wishlist (Software):
    - Lossless Texture Compression Library: dxt-lossless-transform.md
    - Nx2.0 Archive Format: nx2.0.md
  - Wishlist (Site Features): 
    - Send Downloads to Specific Mod Manager: nxm-handler.md
    - Automatic Metadata Parsing: metadata-parsing.md
    - External Notifications for Issue Tracker: issue-tracker.md
    - Batch Tiny File Downloads: tiny-file-downloads.md
    - Release Branches: release-branches.md
    - Blob Storage: blob-storage.md
    - Communicate API Changes: communicate-api-changes.md
    - Collections Support for non-Vortex Software: collections-for-external-software.md